package med.voll.api.domain.medico;

public enum Specialty {
  CARDIOLOGIST,
  DERMATOLOGIST,
  ENDOCRINOLOGIST,
  GASTROENTEROLOGIST,
  GENERAL_PRACTITIONER,
  GYNECOLOGIST,
  HEMATOLOGIST,
  NEUROLOGIST,
  OPHTHALMOLOGIST,
  PEDIATRICIAN,
  PSYCHIATRIST,
  PULMONOLOGIST,
  UROLOGIST
}
